adiciona newsletter desktop e mobile
deco-sites/templaten1 pull request #10
Opened 2023-06-10 14:24 UTC by Erislandio

## What is this contribution about?

Adiciona newsletter desktop e mobile

## Extra info

![Screen Shot 2023-06-10 at 11 20 36](https://github.com/deco-sites/templaten1/assets/34255207/ea684bb1-5717-47df-8cf7-176067e130dd)
![Screen Shot 2023-06-10 at 11 22 20](https://github.com/deco-sites/templaten1/assets/34255207/25e4bc99-171a-4158-a42a-72c287614095)

2023-06-10 14:30 UTC, gustavo-vasconcellos requested changes

2023-06-10 14:30 UTC, gustavo-vasconcellos commented on components/GlobalTags.tsx
> +      <link
Pode remover os Favicons, a maneira certa de fazer é pelo Admin na Section SEO

2023-06-10 14:30 UTC, gustavo-vasconcellos commented on components/footer/Footer.tsx
> +            <Newsletter {...newsletter} />
No caso, a newsletter deve ser uma Section nova, logo tem que ser removida do Footer, atencao na descricaoda task, qualquer duvida me avise

2023-06-10 14:30 UTC, gustavo-vasconcellos commented on components/footer/Newsletter.tsx
> +export interface INewsletterProps {
Mude o nome para Props (seguir padrao)

2023-06-10 14:30 UTC, gustavo-vasconcellos commented on components/footer/Newsletter.tsx
> +export interface INewsletterFormProps {
Muda p nome tambem, pode ser so Form por exemplo.

2023-06-14 14:56 UTC, Erislandio commented
@gustavo-vasconcellos poderia validar novamente

2023-06-14 21:39 UTC, merged