Feature/header layout
deco-sites/templaten1 pull request #4
Opened 2023-06-01 17:58 UTC by raissacmp

## What is this contribution about?

- [x] It should renders the logo and the my account link
- [x] It should have the settings to add each of other sections mentioned above
- [x] It should complies to design of Figma on desktop and mobile version

## Extra info
![Captura de ecrã 2023-06-01 185458](https://github.com/deco-sites/templaten1/assets/62183926/81b7a02e-5623-476e-8194-76ce8d122b8a)

![Captura de ecrã 2023-06-01 185529](https://github.com/deco-sites/templaten1/assets/62183926/531803e6-771f-44dc-a3a5-7698a0317107)

2023-06-01 18:43 UTC, gustavo-vasconcellos requested changes

2023-06-01 18:43 UTC, gustavo-vasconcellos commented on components/header/HeaderLayout.tsx
> +      <div class="flex justify-between items-center h-14 px-5 lg:max-w-[1135px] lg:m-auto lg:h-20 lg:p-0">
@raissacmp Lembra que o Header vai entrar dentro do Container/InnerContainer que voce criou, entao voce nao tem que colocar max-width, margin e etc.

2023-06-01 18:43 UTC, gustavo-vasconcellos commented on components/header/HeaderLayout.tsx
> +} */
@raissacmp Poderia ja deixar pronta as props aqui tipo
```
export interface Props {
  menu: Section
  mobileMenu: Section
...
}
```

2023-06-01 18:43 UTC, gustavo-vasconcellos commented on components/header/HeaderLayout.tsx
> +} */
Colocando as props ja, voce ja consegue chamar o componente `Modals` e enviar as props para ele do menuMobile, minicart e searchBarMobile

2023-06-03 14:56 UTC, raissacmp commented
@gustavo-vasconcellos ajustado!
E header global criado:
![Captura de ecrã 2023-06-03 155536](https://github.com/deco-sites/templaten1/assets/62183926/8e7db3c8-e15e-447e-8c3f-97173e6a758f)
![Captura de ecrã 2023-06-03 155551](https://github.com/deco-sites/templaten1/assets/62183926/50de1c93-df72-49ab-9fd6-de2887e08cf4)

2023-06-05 01:59 UTC, gustavo-vasconcellos commented
Dois detalhes:
- O espaçamento entre o top bar (rosa) e o header (branco) parece grande demais, no layout é bem menor
- O espaçamento entre os icones do minicart e da minha conta tambem parecem maiores do que devia (o fundo cinza do minha conta pode ignorar mesmo)

Revisa os espaçamentos de forma geral e testa em telas maiores tambem para ter certeza que esta tudo certo. A altura fixa que botou no header que pode estar causando isso, tenta deixar com que o conteudo dite a altura do header com paddings e altura natural das coisas, assim o header ficará melhor definido nas proximas tarefas que voce atacará esses pontos ;)

![image](https://github.com/deco-sites/templaten1/assets/29849615/d912a1e5-95eb-4416-af41-02558c2c082d)

2023-06-05 08:31 UTC, raissacmp commented
> Dois detalhes:
> 
> * O espaçamento entre o top bar (rosa) e o header (branco) parece grande demais, no layout é bem menor
> * O espaçamento entre os icones do minicart e da minha conta tambem parecem maiores do que devia (o fundo cinza do minha conta pode ignorar mesmo)
> 
> Revisa os espaçamentos de forma geral e testa em telas maiores tambem para ter certeza que esta tudo certo. A altura fixa que botou no header que pode estar causando isso, tenta deixar com que o conteudo dite a altura do header com paddings e altura natural das coisas, assim o header ficará melhor definido nas proximas tarefas que voce atacará esses pontos ;)
> 
> ![image](https://user-images.githubusercontent.com/29849615/243234298-d912a1e5-95eb-4416-af41-02558c2c082d.png)

>

2023-06-05 08:41 UTC, raissacmp commented
@gustavo-vasconcellos Ajustado! O problema do espaçamento era a altura fixa header mesmo, removi e agora está tudo certo. Sobre o espaçamento entre o icones, nos elementos do header eu não coloquei margem nem padding, assim como conversamos que seria o ideal, então nesse caso somei o espaço que eles ocupavam no figma e ajustei a with, acredito que agora esteja resolvido.

![Captura de ecrã 2023-06-05 093834](https://github.com/deco-sites/templaten1/assets/62183926/c9bf8b61-841f-4a6c-b956-b8321a1bced4)
![Captura de ecrã 2023-06-05 093802](https://github.com/deco-sites/templaten1/assets/62183926/0eef4268-1b2d-450d-93d7-9ee66745124c)

2023-06-05 18:50 UTC, merged